### ISSUE TITLE
preparing raw data for rf study

### ISSUE THREAD

**Issue by datseismo** [PeterMakus/PyGLImER#88] opened 2022-01-22 18:34 UTC
Hii, I have recorded data of a offline station in a directory. How to prepare this station data for receiver functions study(something like 30 to 90 degree ..bla bla).Are there any module exist here to perform this kind of work.Please suggest.

**Comment by PeterMakus** [comment] 2022-01-24 09:27
Hi!
This is something we've meant to implement for a while now (see #78 ).
In principal, all you would need to do is:

1. Download an obspy event catalogue for the times in that your station was active (see [obspy manual](https://docs.obspy.org/packages/autogen/obspy.clients.fdsn.client.Client.get_events.html)
2. You should have some sort of station response file, best would be a [StationXML](https://docs.obspy.org/tutorial/code_snippets/stationxml_file_from_scratch.html)
3. Put them and your waveform data in mseed (if your waveform data is not in mseed you can convert it using either obspy or PyRocko) in a folder structure akin to the one that PyGLImER creates, when setting the ``format`` argument to ``mseed`` (see [PyGLImER's documentation](https://petermakus.github.io/PyGLImER/chapters/creation/requestclass.html).

Actually, it would be a great help for us if you could send us your code after doing so (would save us some time implementing everything ourselves from scratch).

I will close this issue now as it's a duplicate of #78 . You can comment there if you have any further question.

Cheers,
Peter

**Closed by PeterMakus** 2022-01-24 09:27 UTC

**Comment by datseismo** [comment] 2022-01-24 12:41
Ok, if you can show a demo example it would be very helpful.

Thanks

**Comment by PeterMakus** [comment] 2022-01-24 13:42
I'm afraid, I don't really have the time to code this at the moment. Otherwise, I would have implemented this functionality already. (I will probably do that until April)

But if you follow the links I sent you above, you should be able to find some useful instructions and examples on how to proceed with each step. It shouldn't be too difficult.
